name: 'Hello World JS Action'
description: 'Greet someone and record the time'

inputs:
  run_id:
    description: 'The workflow run ID to analyze'
    required: true
  repo_owner:
    description: 'The owner of the repository'
    required: true
  repo_name:
    description: 'The name of the repository'
    required: true
    
outputs:
  time:
    description: 'The time we greeted you'
    
runs:
  using: 'node20'
  main: 'index.js'
  Write-Output "repo_name: "
  Write-Output "run_id:"
