name: 'Hello World JS Action'
description: 'Greet someone and record the time'

inputs:
  run_id:
    description: 'The workflow run ID to analyze'
    required: true
  repo_owner:
    description: 'The owner of the repository'
    required: true
  repo_name:
    description: 'The name of the repository'
    required: true
    
outputs:
  time:
    description: 'The time we greeted you'
    
runs:
  using: 'node20'
  main: 'index.js'

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        run: |
          # Get a list of changed files in the latest push
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Print file contents
        run: |
          echo "Reading file contents:"
          while IFS= read -r file; do
            echo "Content of $file:"
            cat "$file"
            echo ""
          done < changed_files.txt
